import sys
sys.path.insert(0, r'c:\Users\MuthamizhS\OneDrive - Technology Garage\Desktop\Cape New UI\backend')
from config import (
    MIN_RSI_MA_GAP, EXIT_BREAKEVEN_ENABLED, EXIT_BREAKEVEN_TRIGGER_PCT,
    ENTRY_RSI_MOMENTUM_ENABLED, ENTRY_RSI_MIN_DELTA,
    ENTRY_VOLUME_CONFIRMATION_ENABLED, ENTRY_VOLUME_MIN_RATIO,
    ENTRY_RSI_EXTREME_FILTER_ENABLED, ENTRY_RSI_CALL_MAX, ENTRY_RSI_PUT_MIN,
    ENTRY_RSI_STREAK_ENABLED, ENTRY_RSI_MIN_STREAK,
    ENTRY_RSI_CALL_MIN, ENTRY_RSI_PUT_MAX, QP_GAP_PCT,
    EXIT_SAME_CANDLE_MIN_PNL_PCT,
)

print("=== CONFIG VALIDATION ===")
print(f"MIN_RSI_MA_GAP = {MIN_RSI_MA_GAP}")
print(f"ENTRY_RSI_CALL_MIN = {ENTRY_RSI_CALL_MIN}")
print(f"ENTRY_RSI_PUT_MAX = {ENTRY_RSI_PUT_MAX}")
print(f"QP_GAP_PCT = {QP_GAP_PCT}  (dynamic QP locks in at peak − gap%)")
print(f"EXIT_SAME_CANDLE_MIN_PNL_PCT = {EXIT_SAME_CANDLE_MIN_PNL_PCT}")
print(f"EXIT_BREAKEVEN_ENABLED = {EXIT_BREAKEVEN_ENABLED}")
print(f"EXIT_BREAKEVEN_TRIGGER_PCT = {EXIT_BREAKEVEN_TRIGGER_PCT}")
print(f"ENTRY_RSI_MOMENTUM_ENABLED = {ENTRY_RSI_MOMENTUM_ENABLED}")
print(f"ENTRY_RSI_MIN_DELTA = {ENTRY_RSI_MIN_DELTA}")
print(f"ENTRY_VOLUME_CONFIRMATION_ENABLED = {ENTRY_VOLUME_CONFIRMATION_ENABLED}")
print(f"ENTRY_VOLUME_MIN_RATIO = {ENTRY_VOLUME_MIN_RATIO}")
print(f"ENTRY_RSI_EXTREME_FILTER_ENABLED = {ENTRY_RSI_EXTREME_FILTER_ENABLED}")
print(f"ENTRY_RSI_CALL_MAX = {ENTRY_RSI_CALL_MAX}")
print(f"ENTRY_RSI_PUT_MIN = {ENTRY_RSI_PUT_MIN}")
print(f"ENTRY_RSI_STREAK_ENABLED = {ENTRY_RSI_STREAK_ENABLED}")
print(f"ENTRY_RSI_MIN_STREAK = {ENTRY_RSI_MIN_STREAK}")
print("=== ALL OK ===")
